/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphics;

import BD.conexionOracle;
import static BD.conexionOracle.cargarAfiliacionesEnTabla;
import static BD.conexionOracle.cargarAfiliadosEnTabla;
import static BD.conexionOracle.cargarInventarioEnTabla1;
import static BD.conexionOracle.cargarProductosEnTabla;
import static BD.conexionOracle.cargarVendedoresEnTabla;
import static BD.conexionOracle.cargarVentasEnTabla;
import static BD.conexionOracle.verificarDisponibilidad;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YEISON ANDRES MARIN
 */
public class PanelVendedor extends javax.swing.JFrame {

    /**
     * Creates new form PanelVendedor
     */
    private String nombreUsuario;

    // Constructor sin parámetros (por defecto)
    public PanelVendedor() {
        initComponents();
    }

    public PanelVendedor(String nombreUsuario) {

        this.nombreUsuario = nombreUsuario;
        initComponents();

        // Opcional: Mostrar el nombre de usuario en el panel
        System.out.println("Bienvenido, " + nombreUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPaneActualizarInformacion = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelIdVendedor = new javax.swing.JLabel();
        jTextFieldIdVendedor = new javax.swing.JTextField();
        jTextFielNombre = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jTextFieldEstado = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jButtonActualizar = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTabletableListarVendedores = new javax.swing.JTable();
        jButtonlistarVendedores = new javax.swing.JButton();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabelidVendedor = new javax.swing.JLabel();
        jTextFieldidVendedor = new javax.swing.JTextField();
        jLabelNombreAfiliado = new javax.swing.JLabel();
        jTextFieldnombreAfiliado = new javax.swing.JTextField();
        jButtonRegistrarAfiliado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListarAfiliados = new javax.swing.JTable();
        jLabelRegistrarAfiliacion = new javax.swing.JLabel();
        jLabelvendedorId = new javax.swing.JLabel();
        jLabelafiliadoId = new javax.swing.JLabel();
        jTextFieldVendedorI = new javax.swing.JTextField();
        jTextFieldAfiliadoI = new javax.swing.JTextField();
        jButtonRegistrarAfiliacion = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableListarAfiliadosY = new javax.swing.JTable();
        jLabelEliminarAfiliacion = new javax.swing.JLabel();
        jTextFieldEliminarAfiliacion = new javax.swing.JTextField();
        jButtonEliminar = new javax.swing.JButton();
        jButtonLimpiarCampos = new javax.swing.JButton();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabelRegistrarProducto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldidProducto = new javax.swing.JTextField();
        jLabelnombre = new javax.swing.JLabel();
        jLabelprecio = new javax.swing.JLabel();
        jLabelstock = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldStock = new javax.swing.JTextField();
        jButtonRegistrarProducto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDisponibilidad = new javax.swing.JTextField();
        jButtonVerificar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableListarProductos = new javax.swing.JTable();
        jButtonListarProductos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldid_producto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFielcantidad = new javax.swing.JTextField();
        jTextFieldestado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButtonagregarInventario = new javax.swing.JButton();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableInventarioTabla = new javax.swing.JTable();
        jButtonlistarInventario = new javax.swing.JButton();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldidVendedorr = new javax.swing.JTextField();
        jTextFieldProductoo = new javax.swing.JTextField();
        jTextFieldcantidadd = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButtonregistrarVenta = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableListarVentas = new javax.swing.JTable();
        jButtonlistarVentas = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelIdVendedor.setText("Id vendedor");

        jLabelNombre.setText("nombre");

        jLabelEstado.setText("Estado");

        jLabelEmail.setText("Email");

        jLabelTelefono.setText("Telefono");

        jTextFieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonoActionPerformed(evt);
            }
        });

        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        jTabletableListarVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id vendedor", "nombre", "fecha ingreso", "nivel", "estado", "emaill", "telefono", "nombre usuario", "contraseña", "es vip", "afiliados reclutados", "ganancias", "descuentos"
            }
        ));
        jScrollPane6.setViewportView(jTabletableListarVendedores);

        jButtonlistarVendedores.setText("listar vendedores");
        jButtonlistarVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlistarVendedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelNombre)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelEmail)
                                        .addComponent(jLabelEstado)
                                        .addComponent(jLabelTelefono)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(108, 108, 108)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFielNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addComponent(jButtonActualizar))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelIdVendedor)
                                .addGap(84, 84, 84)
                                .addComponent(jTextFieldIdVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonlistarVendedores)
                        .addGap(368, 368, 368)))
                .addComponent(jLabel1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonlistarVendedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelIdVendedor)
                            .addComponent(jTextFieldIdVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFielNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNombre))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEstado)
                            .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEmail)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTelefono))
                        .addGap(50, 50, 50)
                        .addComponent(jButtonActualizar))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPaneActualizarInformacion.addTab("Actualizar informacion", jPanel1);

        jTabbedPane1.addTab("Gestion de perfil", jTabbedPaneActualizarInformacion);

        jLabelidVendedor.setText("id vendedor");

        jTextFieldidVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldidVendedorActionPerformed(evt);
            }
        });

        jLabelNombreAfiliado.setText("Nombre afiliado");

        jTextFieldnombreAfiliado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnombreAfiliadoActionPerformed(evt);
            }
        });

        jButtonRegistrarAfiliado.setText("Registrar afiliado");
        jButtonRegistrarAfiliado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarAfiliadoActionPerformed(evt);
            }
        });

        jTableListarAfiliados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id afiliado", "id_vendedor", "nombre"
            }
        ));
        jScrollPane1.setViewportView(jTableListarAfiliados);

        jLabelRegistrarAfiliacion.setText("Registrar afiliacion");

        jLabelvendedorId.setText("id vendedor");

        jLabelafiliadoId.setText("id afiliado");

        jButtonRegistrarAfiliacion.setText("Registrar Afiliacion");
        jButtonRegistrarAfiliacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarAfiliacionActionPerformed(evt);
            }
        });

        jTableListarAfiliadosY.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id_afiliacion", "id_afiliado", "id_vendedor"
            }
        ));
        jScrollPane3.setViewportView(jTableListarAfiliadosY);

        jLabelEliminarAfiliacion.setText("Eliminar afiliacion");

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonLimpiarCampos.setText("limpiar campos");
        jButtonLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabelRegistrarAfiliacion)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelvendedorId)
                                .addComponent(jLabelafiliadoId))
                            .addGap(228, 228, 228)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldVendedorI)
                                .addComponent(jTextFieldAfiliadoI, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                            .addGap(110, 110, 110)
                            .addComponent(jButtonRegistrarAfiliacion))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabelidVendedor))
                                .addComponent(jLabelNombreAfiliado))
                            .addGap(100, 100, 100)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldidVendedor)
                                .addComponent(jTextFieldnombreAfiliado, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                            .addGap(165, 165, 165)
                            .addComponent(jButtonRegistrarAfiliado))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEliminar)
                        .addGap(205, 205, 205))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabelEliminarAfiliacion)
                                .addGap(94, 94, 94)
                                .addComponent(jTextFieldEliminarAfiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jButtonLimpiarCampos)))
                        .addContainerGap(67, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelidVendedor)
                            .addComponent(jTextFieldidVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonRegistrarAfiliado)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelEliminarAfiliacion)
                                .addComponent(jTextFieldEliminarAfiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreAfiliado)
                    .addComponent(jTextFieldnombreAfiliado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButtonEliminar)))
                .addGap(29, 29, 29)
                .addComponent(jLabelRegistrarAfiliacion)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelvendedorId)
                            .addComponent(jTextFieldVendedorI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButtonRegistrarAfiliacion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelafiliadoId)
                    .addComponent(jTextFieldAfiliadoI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonLimpiarCampos)
                        .addGap(82, 82, 82))))
        );

        jTabbedPane4.addTab("Registrar afiliado", jPanel2);

        jTabbedPane1.addTab("Gestion de afiliados", jTabbedPane4);

        jLabelRegistrarProducto.setText("Registrar producto");

        jLabel2.setText("id del producto");

        jLabelnombre.setText("nombre");

        jLabelprecio.setText("precio");

        jLabelstock.setText("stock");

        jButtonRegistrarProducto.setText("Registrar");
        jButtonRegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarProductoActionPerformed(evt);
            }
        });

        jLabel3.setText("Verificar disponibilidad");

        jLabel4.setText("id del producto");

        jButtonVerificar.setText("verificar");
        jButtonVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerificarActionPerformed(evt);
            }
        });

        jLabel5.setText("Listar productos");

        jTableListarProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id producto", "nombre", "precio", "stock"
            }
        ));
        jScrollPane4.setViewportView(jTableListarProductos);

        jButtonListarProductos.setText("listar");
        jButtonListarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarProductosActionPerformed(evt);
            }
        });

        jLabel6.setText("id producto");

        jLabel7.setText("cantidad");

        jLabel8.setText("estado");

        jTextFielcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielcantidadActionPerformed(evt);
            }
        });

        jTextFieldestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldestadoActionPerformed(evt);
            }
        });

        jLabel9.setText("agregar producto al inventario");

        jButtonagregarInventario.setText("Agregar");
        jButtonagregarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonagregarInventarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabelRegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(399, 399, 399)
                        .addComponent(jLabel3)
                        .addGap(118, 118, 118)
                        .addComponent(jButtonVerificar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabelnombre)
                            .addComponent(jLabelprecio)
                            .addComponent(jLabelstock))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldidProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombre)
                            .addComponent(jTextFieldPrecio)
                            .addComponent(jTextFieldStock))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(332, 332, 332)
                                .addComponent(jLabel4)
                                .addGap(50, 50, 50)
                                .addComponent(jTextFieldDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(389, 389, 389)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7))
                                        .addGap(82, 82, 82))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addGap(68, 68, 68)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldestado, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFielcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldid_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jButtonRegistrarProducto)
                                .addGap(277, 277, 277)
                                .addComponent(jLabel9))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel5)
                        .addGap(60, 60, 60)
                        .addComponent(jButtonListarProductos))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217)
                        .addComponent(jButtonagregarInventario)))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabelRegistrarProducto))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel3)))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextFieldidProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonVerificar)
                                .addGap(6, 6, 6)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextFieldDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelnombre)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButtonRegistrarProducto)
                                            .addComponent(jLabel9))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelprecio)
                                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelstock)
                                    .addComponent(jTextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel6))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jTextFieldid_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jButtonListarProductos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFielcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonagregarInventario)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Gestionar productos y mas", jPanel3);

        jTabbedPane1.addTab("Gestion de productos", jTabbedPane5);

        jTableInventarioTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id inventario", "id producto", "cantidad", "estado", "maxima cantidad"
            }
        ));
        jScrollPane5.setViewportView(jTableInventarioTabla);

        jButtonlistarInventario.setText("listar inventario");
        jButtonlistarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlistarInventarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(jButtonlistarInventario)))
                .addContainerGap(498, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButtonlistarInventario)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("inventario y mas", jPanel5);

        jTabbedPane1.addTab("inventario", jTabbedPane6);
        jTabbedPane1.addTab("Despachos", jTabbedPane7);

        jLabel10.setText("id vendedor");

        jLabel12.setText("cantidad");

        jTextFieldidVendedorr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldidVendedorrActionPerformed(evt);
            }
        });

        jTextFieldProductoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProductooActionPerformed(evt);
            }
        });

        jLabel13.setText("id del producto");

        jButtonregistrarVenta.setText("Registrar venta");
        jButtonregistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonregistrarVentaActionPerformed(evt);
            }
        });

        jLabel14.setText("Listar ventas");

        jTableListarVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id venta", "id vendedor", "id producto", "cantidad", "fecha venta", "total venta", "estado"
            }
        ));
        jScrollPane7.setViewportView(jTableListarVentas);

        jButtonlistarVentas.setText("Listar ventas");
        jButtonlistarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlistarVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jButtonregistrarVenta))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(509, 509, 509)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonlistarVentas)
                .addGap(265, 265, 265))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(157, 157, 157)
                                .addComponent(jTextFieldidVendedorr, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(182, 182, 182))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11)
                                        .addGap(125, 125, 125)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldProductoo, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(jTextFieldcantidadd)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldidVendedorr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldProductoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldcantidadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButtonregistrarVenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButtonlistarVentas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("ventas y mas", jPanel4);

        jTabbedPane1.addTab("Gestion de ventas", jTabbedPane2);

        jButtonSalir.setText("Salir ----->");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonVolver.setText("<---- volver menu principal");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 663, Short.MAX_VALUE)
                .addComponent(jButtonSalir)
                .addGap(228, 228, 228))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalir)
                    .addComponent(jButtonVolver))
                .addContainerGap(502, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("", jPanel6);

        jTabbedPane1.addTab("Salir", jTabbedPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed

        // Obtener los valores de los campos del formulario
        String idVendedorStr = jTextFieldIdVendedor.getText();
        String nombre = jTextFielNombre.getText();
        String estado = jTextFieldEstado.getText();
        String email = jTextFieldEmail.getText();
        String telefono = jTextFieldTelefono.getText();

// Validar que no haya campos vacíos
        if (idVendedorStr.isEmpty() || nombre.isEmpty() || estado.isEmpty() || email.isEmpty() || telefono.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // Salir del método si algún campo está vacío
        }

        try {
            // Convertir el idVendedor a un entero
            int idVendedor = Integer.parseInt(idVendedorStr);

            // Llamar al método que actualiza al vendedor en la base de datos
            conexionOracle conexion = new conexionOracle();
            conexion.conectar();
            conexion.actualizarVendedor(idVendedor, nombre, estado, email, telefono);

            // Mostrar mensaje de éxito
            javax.swing.JOptionPane.showMessageDialog(this, "Vendedor actualizado exitosamente.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            conexion.desconectar();

            // Limpiar los campos del formulario
            jTextFieldIdVendedor.setText("");
            jTextFielNombre.setText("");
            jTextFieldEstado.setText("");
            jTextFieldEmail.setText("");
            jTextFieldTelefono.setText("");

        } catch (NumberFormatException e) {
            // Manejar el error si el idVendedor no es un número válido
            javax.swing.JOptionPane.showMessageDialog(this, "El ID del vendedor debe ser un número entero.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            // Manejar otros errores generales
            javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar la información del vendedor: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jTextFieldidVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldidVendedorActionPerformed

        jTextFieldnombreAfiliado.requestFocus();


    }//GEN-LAST:event_jTextFieldidVendedorActionPerformed

    private void jButtonRegistrarAfiliadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarAfiliadoActionPerformed

        // Obtener los valores de los campos del formulario
        String idVendedorStr = jTextFieldidVendedor.getText().trim(); // Eliminar espacios en blanco
        String nombreAfiliado = jTextFieldnombreAfiliado.getText().trim(); // Eliminar espacios en blanco

        // DEBUG: Imprimir valores capturados
        System.out.println("ID Vendedor: '" + idVendedorStr + "'");
        System.out.println("Nombre Afiliado: '" + nombreAfiliado + "'");

        // Validar que no haya campos vacíos
        if (idVendedorStr.isEmpty() || nombreAfiliado.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, completa todos los campos.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // Salir del método si algún campo está vacío
        }

        try {
            // Convertir el idVendedor a un entero
            int idVendedor = Integer.parseInt(idVendedorStr);

            // Llamar al método que registra al afiliado en la base de datos
            conexionOracle conexion = new conexionOracle();
            conexion.conectar();
            conexion.registrarAfiliado(idVendedor, nombreAfiliado);

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Afiliado registrado exitosamente.",
                    "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Actualizar el JTable para mostrar los afiliados
            cargarAfiliadosEnTabla(jTableListarAfiliados);

            // Limpiar los campos del formulario
            jTextFieldIdVendedor.setText("");
            jTextFieldnombreAfiliado.setText("");

            conexion.desconectar();

        } catch (NumberFormatException e) {
            // Manejar el error si el idVendedor no es un número válido
            javax.swing.JOptionPane.showMessageDialog(this,
                    "El ID del vendedor debe ser un número entero.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {

            // Manejar otros errores generales
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al registrar el afiliado: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_jButtonRegistrarAfiliadoActionPerformed

    private void jTextFieldnombreAfiliadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnombreAfiliadoActionPerformed

        jButtonRegistrarAfiliado.doClick();


    }//GEN-LAST:event_jTextFieldnombreAfiliadoActionPerformed

    private void jButtonRegistrarAfiliacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarAfiliacionActionPerformed

        // Obtener los valores de los campos del formulario
        String idVendedorStr = jTextFieldVendedorI.getText().trim(); // ID del vendedor
        String idAfiliadoStr = jTextFieldAfiliadoI.getText().trim(); // ID del afiliado

        // DEBUG: Imprimir valores capturados (opcional para depuración)
        System.out.println("ID Vendedor: '" + idVendedorStr + "'");
        System.out.println("ID Afiliado: '" + idAfiliadoStr + "'");

        // Validar que no haya campos vacíos
        if (idVendedorStr.isEmpty() || idAfiliadoStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, completa todos los campos.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // Salir del método si algún campo está vacío
        }

        try {
            // Convertir los valores a enteros
            int idVendedor = Integer.parseInt(idVendedorStr);
            int idAfiliado = Integer.parseInt(idAfiliadoStr);

            // Llamar al método que registra la afiliación en la base de datos
            conexionOracle conexion = new conexionOracle();
            conexion.conectar();
            conexion.registrarAfiliacion(idVendedor, idAfiliado);

            // Mostrar mensaje de éxito
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Afiliación registrada exitosamente.",
                    "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Actualizar componentes gráficos si es necesario
            cargarAfiliacionesEnTabla(jTableListarAfiliadosY);
            // Limpiar los campos del formulario
            jTextFieldVendedorI.setText("");
            jTextFieldAfiliadoI.setText("");

            conexion.desconectar();
        } catch (NumberFormatException e) {
            // Manejar el error si los IDs no son números válidos
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Los campos deben contener valores numéricos válidos.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {

            // Manejar otros errores generales
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al registrar la afiliación: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_jButtonRegistrarAfiliacionActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed

        // Obtener el ID de la afiliación desde un campo de texto o tabla
        String idAfiliacionStr = jTextFieldEliminarAfiliacion.getText().trim();

        if (idAfiliacionStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, ingresa el ID de la afiliación a eliminar.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            int idAfiliacion = Integer.parseInt(idAfiliacionStr);

            // Llamar al método para eliminar afiliado
            conexionOracle conexion = new conexionOracle();
            conexion.conectar();
            conexion.eliminarAfiliado(idAfiliacion);

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Afiliado eliminado correctamente.",
                    "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            // Actualizar la tabla después de eliminar
            cargarAfiliacionesEnTabla(jTableListarAfiliados);

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "El ID de afiliación debe ser un número válido.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al eliminar el afiliado: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonRegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarProductoActionPerformed

        // Obtener los valores de los campos del formulario
        String idProductoStr = jTextFieldidProducto.getText().trim(); // Eliminar espacios en blanco
        String nombreProducto = jTextFieldNombre.getText().trim();     // Eliminar espacios en blanco
        String precioStr = jTextFieldPrecio.getText().trim();          // Eliminar espacios en blanco
        String stockStr = jTextFieldStock.getText().trim();

        // DEBUG: Imprimir valores capturados
        System.out.println("ID Producto: '" + idProductoStr + "'");
        System.out.println("Nombre Producto: '" + nombreProducto + "'");
        System.out.println("Precio: '" + precioStr + "'");
        System.out.println("Stock: '" + stockStr + "'");

        // Validar que no haya campos vacíos
        if (idProductoStr.isEmpty() || nombreProducto.isEmpty() || precioStr.isEmpty() || stockStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, completa todos los campos.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // Salir del método si algún campo está vacío
        }

        try {
            // Convertir los campos a los tipos adecuados
            int idProducto = Integer.parseInt(idProductoStr);
            double precio = Double.parseDouble(precioStr);
            int stock = Integer.parseInt(stockStr);

            // Llamar al método que registra el producto en la base de datos
            conexionOracle conexion = new conexionOracle();
            conexion.conectar();
            String resultado = conexion.registrarProducto(idProducto, nombreProducto, precio, stock);

            // Mostrar el resultado de la función
            if ("Éxito".equals(resultado) || resultado.isEmpty()) {  // Verifica si el resultado es "Éxito" o vacío
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Producto registrado exitosamente.",
                        "Éxito",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Error: " + resultado,
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }

            // Limpiar los campos del formulario
            jTextFieldidProducto.setText("");
            jTextFieldNombre.setText("");
            jTextFieldPrecio.setText("");
            jTextFieldStock.setText("");

            conexion.desconectar();

        } catch (NumberFormatException e) {
            // Manejar el error si alguno de los valores no es válido
            javax.swing.JOptionPane.showMessageDialog(this,
                    "El ID del producto, precio o stock deben ser valores numéricos válidos.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {

            // Manejar otros errores generales
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al registrar el producto: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_jButtonRegistrarProductoActionPerformed

    private void jButtonListarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarProductosActionPerformed

        try {
            // Llamar al método para cargar los productos en la tabla
            cargarProductosEnTabla(jTableListarProductos);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al listar los productos: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButtonListarProductosActionPerformed

    private void jButtonVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerificarActionPerformed

        // Obtener el valor del ID del producto desde un campo de texto
        String idProductoStr = jTextFieldDisponibilidad.getText().trim();

        // Validar que el campo no esté vacío
        if (idProductoStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, ingresa un ID de producto válido.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Convertir el ID del producto a entero
            int idProducto = Integer.parseInt(idProductoStr);

            // Llamar a la función para verificar la disponibilidad
            int disponibilidad = verificarDisponibilidad(idProducto);

            // Mostrar el resultado en el jTextFieldDisponibilidad
            if (disponibilidad > 0) {
                jTextFieldDisponibilidad.setText("Disponible");
            } else {
                jTextFieldDisponibilidad.setText("No disponible");
            }
        } catch (NumberFormatException e) {
            // Manejar el error si el ID del producto no es un número válido
            javax.swing.JOptionPane.showMessageDialog(this,
                    "El ID del producto debe ser un número entero.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            // Manejar otros errores generales
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al verificar la disponibilidad: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButtonVerificarActionPerformed

    private void jTextFielcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielcantidadActionPerformed

    private void jTextFieldestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldestadoActionPerformed

    private void jButtonagregarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonagregarInventarioActionPerformed

        // Obtener los valores de los campos de texto
        String idProductoStr = jTextFieldid_producto.getText().trim();
        String cantidadStr = jTextFielcantidad.getText().trim();
        String estado = jTextFieldestado.getText().trim(); // Opcional: Puede estar vacío

        // Validar que los campos requeridos no estén vacíos
        if (idProductoStr.isEmpty() || cantidadStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, completa todos los campos requeridos (ID Producto y Cantidad).",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Convertir los valores a sus tipos adecuados
            int idProducto = Integer.parseInt(idProductoStr);
            int cantidad = Integer.parseInt(cantidadStr);

            // Llamar al método para agregar el producto al inventario
            conexionOracle conexion = new conexionOracle();
            conexion.conectar();
            conexion.agregarProductoInventario(idProducto, cantidad, estado);

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Producto agregado al inventario exitosamente.",
                    "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Limpiar los campos después de agregar
            jTextFieldid_producto.setText("");
            jTextFielcantidad.setText("");
            jTextFieldestado.setText(""); // Opcional: Borra el estado ingresado

            conexion.desconectar();

        } catch (NumberFormatException e) {
            // Manejar errores de formato de números
            javax.swing.JOptionPane.showMessageDialog(this,
                    "El ID del producto y la cantidad deben ser números válidos.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);

        } catch (SQLException e) {
            // Manejar errores de SQL
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al agregar el producto al inventario: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);

        } catch (Exception e) {
            // Manejar errores generales
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error inesperado: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButtonagregarInventarioActionPerformed

    private void jTextFieldidVendedorrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldidVendedorrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldidVendedorrActionPerformed

    private void jTextFieldProductooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProductooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductooActionPerformed

    private void jButtonregistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonregistrarVentaActionPerformed

        // Obtener los valores de los campos de texto
        String idVendedorStr = jTextFieldidVendedorr.getText().trim();
        String idProductoStr = jTextFieldProductoo.getText().trim();
        String cantidadStr = jTextFieldcantidadd.getText().trim();

        // Validar que no haya campos vacíos
        if (idVendedorStr.isEmpty() || idProductoStr.isEmpty() || cantidadStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, completa todos los campos (ID Vendedor, ID Producto y Cantidad).",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Convertir los valores a sus tipos adecuados
            int idVendedor = Integer.parseInt(idVendedorStr);
            int idProducto = Integer.parseInt(idProductoStr);
            int cantidad = Integer.parseInt(cantidadStr);

            // Llamar al método para registrar la venta
            conexionOracle conexion = new conexionOracle();
            conexion.conectar();
            conexion.registrarVenta(idVendedor, idProducto, cantidad);

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Venta registrada exitosamente.",
                    "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Limpiar los campos después de registrar
            jTextFieldidVendedorr.setText("");
            jTextFieldProductoo.setText("");
            jTextFieldcantidadd.setText("");

            conexion.desconectar();
        } catch (NumberFormatException e) {
            // Manejo de errores en los datos ingresados
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Los campos ID Vendedor, ID Producto y Cantidad deben ser números válidos.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            // Manejo de errores SQL
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al registrar la venta: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {

            // Manejo de errores generales
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error inesperado: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_jButtonregistrarVentaActionPerformed

    private void jButtonlistarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlistarInventarioActionPerformed

        try {
            // Llamar al método para cargar los datos del inventario en la tabla
            cargarInventarioEnTabla1(jTableInventarioTabla);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al cargar los datos del inventario: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButtonlistarInventarioActionPerformed

    private void jButtonlistarVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlistarVendedoresActionPerformed

        try {
            // Llamar al método para cargar los datos de los vendedores en la tabla
            cargarVendedoresEnTabla(jTabletableListarVendedores);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al listar los vendedores: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButtonlistarVendedoresActionPerformed

    private void jButtonLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarCamposActionPerformed

        // Limpiar todos los JTextField relacionados con la gestión de afiliados
        jTextFieldidVendedor.setText("");
        jTextFieldnombreAfiliado.setText("");
        jTextFieldid_producto.setText("");
        jTextFielcantidad.setText("");
        jTextFieldestado.setText("");
        jTextFieldDisponibilidad.setText("");
        jTextFieldPrecio.setText("");
        jTextFieldStock.setText("");
        jTextFieldNombre.setText("");

        // Mostrar un mensaje indicando que los campos fueron limpiados
        javax.swing.JOptionPane.showMessageDialog(this,
                "Todos los campos han sido limpiados.",
                "Limpieza Exitosa",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_jButtonLimpiarCamposActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed

        // Confirmación antes de salir
        int opcion = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Estás seguro de que deseas salir?",
                "Confirmar salida",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE);

        // Si el usuario confirma, cierra el panel
        if (opcion == javax.swing.JOptionPane.YES_OPTION) {
            // Salir del programa o cerrar el panel
            System.exit(0); // Cierra la aplicación
            // Alternativamente, si estás dentro de un JFrame:
            // this.dispose(); // Cierra solo el JFrame actual
        }


    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonlistarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlistarVentasActionPerformed
        
        
        try {
        // Llamar al método para cargar las ventas en la tabla
        cargarVentasEnTabla(jTableListarVentas);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Error al listar las ventas: " + e.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButtonlistarVentasActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        
        
        
        
         // Crear y mostrar la ventana de Login
        MenuPrincipalForm menu = new MenuPrincipalForm();// Crea una instancia del formulario de login
        menu.setVisible(true);  // Muestra la ventana de login

        // Si deseas que el formulario principal se cierre cuando se abre el login:
        setVisible(false);  // Esto ocultará el formulario actual (menuPrincipalForm)
        dispose();  // 
    }//GEN-LAST:event_jButtonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonLimpiarCampos;
    private javax.swing.JButton jButtonListarProductos;
    private javax.swing.JButton jButtonRegistrarAfiliacion;
    private javax.swing.JButton jButtonRegistrarAfiliado;
    private javax.swing.JButton jButtonRegistrarProducto;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVerificar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JButton jButtonagregarInventario;
    private javax.swing.JButton jButtonlistarInventario;
    private javax.swing.JButton jButtonlistarVendedores;
    private javax.swing.JButton jButtonlistarVentas;
    private javax.swing.JButton jButtonregistrarVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelEliminarAfiliacion;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelIdVendedor;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombreAfiliado;
    private javax.swing.JLabel jLabelRegistrarAfiliacion;
    private javax.swing.JLabel jLabelRegistrarProducto;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelafiliadoId;
    private javax.swing.JLabel jLabelidVendedor;
    private javax.swing.JLabel jLabelnombre;
    private javax.swing.JLabel jLabelprecio;
    private javax.swing.JLabel jLabelstock;
    private javax.swing.JLabel jLabelvendedorId;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTabbedPane jTabbedPaneActualizarInformacion;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableInventarioTabla;
    private javax.swing.JTable jTableListarAfiliados;
    private javax.swing.JTable jTableListarAfiliadosY;
    private javax.swing.JTable jTableListarProductos;
    private javax.swing.JTable jTableListarVentas;
    private javax.swing.JTable jTabletableListarVendedores;
    private javax.swing.JTextField jTextFielNombre;
    private javax.swing.JTextField jTextFielcantidad;
    private javax.swing.JTextField jTextFieldAfiliadoI;
    private javax.swing.JTextField jTextFieldDisponibilidad;
    private javax.swing.JTextField jTextFieldEliminarAfiliacion;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldIdVendedor;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldProductoo;
    private javax.swing.JTextField jTextFieldStock;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextFieldVendedorI;
    private javax.swing.JTextField jTextFieldcantidadd;
    private javax.swing.JTextField jTextFieldestado;
    private javax.swing.JTextField jTextFieldidProducto;
    private javax.swing.JTextField jTextFieldidVendedor;
    private javax.swing.JTextField jTextFieldidVendedorr;
    private javax.swing.JTextField jTextFieldid_producto;
    private javax.swing.JTextField jTextFieldnombreAfiliado;
    // End of variables declaration//GEN-END:variables
}
